baseURL                = 'https://example.org/'
languageCode           = 'zh-cn'
defaultContentLanguage = "zh"
pluralizeListTitles    = false
title                  = "Urtusea CP-Algorithm"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
    # 主题颜色
    BookTheme   = 'dark'

    # 文档位置
    BookSection = '*'

    # 查找功能
    BookSearch = true